name: testing
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.18.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/testing/assets/images/group.svg
    - packages/testing/assets/images/xmlid511.svg
    - packages/testing/assets/images/vector.svg
    - packages/testing/assets/images/dot.svg
    - packages/testing/assets/images/img.png
    - packages/testing/assets/images/home.svg
    - packages/testing/assets/images/graph.svg
    - packages/testing/assets/images/adduser.svg
    - packages/testing/assets/images/setting.svg
    - packages/testing/assets/images/ellipse1.png
    - packages/testing/assets/images/rectangle1.png
    - packages/testing/assets/images/menu.svg
    - packages/testing/assets/images/ionarrowback.svg
    - packages/testing/assets/images/rectangle10.svg
    - packages/testing/assets/images/rectangle11.svg
    - packages/testing/assets/images/fill1.svg
    - packages/testing/assets/images/combinedshape.svg
    - packages/testing/assets/images/rectangle6.png
    - packages/testing/assets/images/jogging1.svg
    - packages/testing/assets/images/frame4.svg
    - packages/testing/assets/images/ellipse.png
    - packages/testing/assets/images/avatar.png
    - packages/testing/assets/images/rectangle7.svg
    - packages/testing/assets/images/path2357.svg
    - packages/testing/assets/images/path2358.svg
    - packages/testing/assets/images/path2361.svg
    - packages/testing/assets/images/path2362.svg
    - packages/testing/assets/images/path2363.svg
    - packages/testing/assets/images/path2364.svg
    - packages/testing/assets/images/path2365.svg
    - packages/testing/assets/images/path2366.svg
    - packages/testing/assets/images/path2367.svg
    - packages/testing/assets/images/path2368.svg
    - packages/testing/assets/images/path2369.svg
    - packages/testing/assets/images/path2370.svg
    - packages/testing/assets/images/path2371.svg
    - packages/testing/assets/images/path2372.svg
    - packages/testing/assets/images/path2373.svg
    - packages/testing/assets/images/group51.svg
    - packages/testing/assets/images/group52.svg
    - packages/testing/assets/images/group53.svg
    - packages/testing/assets/images/group54.svg
    - packages/testing/assets/images/group55.svg
    - packages/testing/assets/images/group56.svg
    - packages/testing/assets/images/group57.svg
    - packages/testing/assets/images/path2603.svg
    - packages/testing/assets/images/group58.svg
    - packages/testing/assets/images/group59.svg
    - packages/testing/assets/images/group60.svg
    - packages/testing/assets/images/group61.svg
    - packages/testing/assets/images/path2817.svg
    - packages/testing/assets/images/path2818.svg
    - packages/testing/assets/images/path3335.svg
    - packages/testing/assets/images/path3336.svg
    - packages/testing/assets/images/group63.svg
    - packages/testing/assets/images/group64.svg
    - packages/testing/assets/images/group65.svg
    - packages/testing/assets/images/group66.svg
    - packages/testing/assets/images/path3970.svg
    - packages/testing/assets/images/path3971.svg
    - packages/testing/assets/images/path3972.svg
    - packages/testing/assets/images/path3973.svg
    - packages/testing/assets/images/path3974.svg
    - packages/testing/assets/images/path3975.svg
    - packages/testing/assets/images/path3976.svg
    - packages/testing/assets/images/group67.svg
    - packages/testing/assets/images/path3979.svg
    - packages/testing/assets/images/path3980.svg
    - packages/testing/assets/images/path3981.svg
    - packages/testing/assets/images/path3982.svg
    - packages/testing/assets/images/group68.svg
    - packages/testing/assets/images/path3983.svg
    - packages/testing/assets/images/path3984.svg
    - packages/testing/assets/images/path3985.svg
    - packages/testing/assets/images/path3986.svg
    - packages/testing/assets/images/group69.svg
    - packages/testing/assets/images/group70.svg
    - packages/testing/assets/images/ellipse17.svg
    - packages/testing/assets/images/ellipse18.svg
    - packages/testing/assets/images/path4097.svg
    - packages/testing/assets/images/group71.svg
    - packages/testing/assets/images/path4100.svg
    - packages/testing/assets/images/path4101.svg
    - packages/testing/assets/images/path4102.svg
    - packages/testing/assets/images/group72.svg
    - packages/testing/assets/images/path4106.svg
    - packages/testing/assets/images/path4107.svg
    - packages/testing/assets/images/group73.svg
    - packages/testing/assets/images/path4325.svg
    - packages/testing/assets/images/path4326.svg
    - packages/testing/assets/images/group74.svg
    - packages/testing/assets/images/path4339.svg
    - packages/testing/assets/images/path4340.svg
    - packages/testing/assets/images/group75.svg
    - packages/testing/assets/images/path4361.svg
    - packages/testing/assets/images/path4362.svg
    - packages/testing/assets/images/path4363.svg
    - packages/testing/assets/images/path4364.svg
    - packages/testing/assets/images/group76.svg
    - packages/testing/assets/images/path4370.svg
    - packages/testing/assets/images/path4371.svg
    - packages/testing/assets/images/ellipse19.svg
    - packages/testing/assets/images/path4372.svg
    - packages/testing/assets/images/ellipse20.svg
    - packages/testing/assets/images/path4373.svg
    - packages/testing/assets/images/path4374.svg
    - packages/testing/assets/images/group77.svg
    - packages/testing/assets/images/group78.svg
    - packages/testing/assets/images/group79.svg
    - packages/testing/assets/images/path4396.svg
    - packages/testing/assets/images/group80.svg
    - packages/testing/assets/images/path4397.svg
    - packages/testing/assets/images/path4398.svg
    - packages/testing/assets/images/group81.svg
    - packages/testing/assets/images/path4401.svg
    - packages/testing/assets/images/group82.svg
    - packages/testing/assets/images/path4446.svg
    - packages/testing/assets/images/path4448.svg
    - packages/testing/assets/images/path4449.svg
    - packages/testing/assets/images/path4450.svg
    - packages/testing/assets/images/group83.svg
    - packages/testing/assets/images/group84.svg
    - packages/testing/assets/images/path4492.svg
    - packages/testing/assets/images/path4493.svg
    - packages/testing/assets/images/path4494.svg
    - packages/testing/assets/images/group85.svg
    - packages/testing/assets/images/group86.svg
    - packages/testing/assets/images/path4500.svg
    - packages/testing/assets/images/path4501.svg
    - packages/testing/assets/images/group87.svg
    - packages/testing/assets/images/path4504.svg
    - packages/testing/assets/images/path4505.svg
    - packages/testing/assets/images/group88.svg
    - packages/testing/assets/images/ellipse23.svg
    - packages/testing/assets/images/path4510.svg
    - packages/testing/assets/images/path4511.svg
    - packages/testing/assets/images/group89.svg
    - packages/testing/assets/images/ellipse24.svg
    - packages/testing/assets/images/path4516.svg
    - packages/testing/assets/images/group90.svg
    - packages/testing/assets/images/path4519.svg
    - packages/testing/assets/images/path4520.svg
    - packages/testing/assets/images/path4521.svg
    - packages/testing/assets/images/path4522.svg
    - packages/testing/assets/images/path4523.svg
    - packages/testing/assets/images/path4524.svg
    - packages/testing/assets/images/path4525.svg
    - packages/testing/assets/images/path4526.svg
    - packages/testing/assets/images/path4527.svg
    - packages/testing/assets/images/path4528.svg
    - packages/testing/assets/images/path4529.svg
    - packages/testing/assets/images/path4530.svg
    - packages/testing/assets/images/path4531.svg
    - packages/testing/assets/images/path4532.svg
    - packages/testing/assets/images/path4533.svg
    - packages/testing/assets/images/group91.svg
    - packages/testing/assets/images/group92.svg
    - packages/testing/assets/images/path4581.svg
    - packages/testing/assets/images/path4582.svg
    - packages/testing/assets/images/group93.svg
    - packages/testing/assets/images/path4584.svg
    - packages/testing/assets/images/path4585.svg
    - packages/testing/assets/images/path4586.svg
    - packages/testing/assets/images/group94.svg
    - packages/testing/assets/images/path4590.svg
    - packages/testing/assets/images/path4591.svg
    - packages/testing/assets/images/path4592.svg
    - packages/testing/assets/images/group95.svg
    - packages/testing/assets/images/ellipse26.svg
    - packages/testing/assets/images/ellipse27.svg
    - packages/testing/assets/images/path4603.svg
    - packages/testing/assets/images/path4604.svg
    - packages/testing/assets/images/group96.svg
    - packages/testing/assets/images/path4612.svg
    - packages/testing/assets/images/path4613.svg
    - packages/testing/assets/images/path4614.svg
    - packages/testing/assets/images/path4616.svg
    - packages/testing/assets/images/path4617.svg
    - packages/testing/assets/images/path4618.svg
    - packages/testing/assets/images/path4619.svg
    - packages/testing/assets/images/path4620.svg
    - packages/testing/assets/images/path4621.svg
    - packages/testing/assets/images/path4622.svg
    - packages/testing/assets/images/group97.svg
    - packages/testing/assets/images/group98.svg
    - packages/testing/assets/images/group99.svg
    - packages/testing/assets/images/group100.svg
    - packages/testing/assets/images/group101.svg
    - packages/testing/assets/images/path4722.svg
    - packages/testing/assets/images/group102.svg
    - packages/testing/assets/images/group103.svg
    - packages/testing/assets/images/group104.svg
    - packages/testing/assets/images/path4759.svg
    - packages/testing/assets/images/path4760.svg
    - packages/testing/assets/images/path4761.svg
    - packages/testing/assets/images/group105.svg
    - packages/testing/assets/images/path4764.svg
    - packages/testing/assets/images/path2006.svg
    - packages/testing/assets/images/path2007.svg
    - packages/testing/assets/images/path2008.svg
    - packages/testing/assets/images/path2009.svg
    - packages/testing/assets/images/path2010.svg
    - packages/testing/assets/images/path2011.svg
    - packages/testing/assets/images/group26.svg
    - packages/testing/assets/images/group27.svg
    - packages/testing/assets/images/group28.svg
    - packages/testing/assets/images/path2025.svg
    - packages/testing/assets/images/path2026.svg
    - packages/testing/assets/images/path2027.svg
    - packages/testing/assets/images/group29.svg
    - packages/testing/assets/images/path2030.svg
    - packages/testing/assets/images/path2031.svg
    - packages/testing/assets/images/ellipse10.svg
    - packages/testing/assets/images/ellipse11.svg
    - packages/testing/assets/images/path2032.svg
    - packages/testing/assets/images/group30.svg
    - packages/testing/assets/images/group31.svg
    - packages/testing/assets/images/path2095.svg
    - packages/testing/assets/images/path2096.svg
    - packages/testing/assets/images/path2097.svg
    - packages/testing/assets/images/path2098.svg
    - packages/testing/assets/images/path2099.svg
    - packages/testing/assets/images/path2100.svg
    - packages/testing/assets/images/path2101.svg
    - packages/testing/assets/images/path2102.svg
    - packages/testing/assets/images/group32.svg
    - packages/testing/assets/images/path2105.svg
    - packages/testing/assets/images/path2106.svg
    - packages/testing/assets/images/path2107.svg
    - packages/testing/assets/images/group33.svg
    - packages/testing/assets/images/path2110.svg
    - packages/testing/assets/images/path2111.svg
    - packages/testing/assets/images/path2112.svg
    - packages/testing/assets/images/path2113.svg
    - packages/testing/assets/images/path2114.svg
    - packages/testing/assets/images/group34.svg
    - packages/testing/assets/images/path2119.svg
    - packages/testing/assets/images/path2120.svg
    - packages/testing/assets/images/path2121.svg
    - packages/testing/assets/images/group35.svg
    - packages/testing/assets/images/group36.svg
    - packages/testing/assets/images/path2136.svg
    - packages/testing/assets/images/group37.svg
    - packages/testing/assets/images/group38.svg
    - packages/testing/assets/images/group39.svg
    - packages/testing/assets/images/path2193.svg
    - packages/testing/assets/images/path2194.svg
    - packages/testing/assets/images/group40.svg
    - packages/testing/assets/images/group41.svg
    - packages/testing/assets/images/group42.svg
    - packages/testing/assets/images/path2230.svg
    - packages/testing/assets/images/path2231.svg
    - packages/testing/assets/images/path2232.svg
    - packages/testing/assets/images/path2233.svg
    - packages/testing/assets/images/path2234.svg
    - packages/testing/assets/images/path2235.svg
    - packages/testing/assets/images/path2236.svg
    - packages/testing/assets/images/path2237.svg
    - packages/testing/assets/images/path2238.svg
    - packages/testing/assets/images/path2239.svg
    - packages/testing/assets/images/path2240.svg
    - packages/testing/assets/images/path2241.svg
    - packages/testing/assets/images/path2242.svg
    - packages/testing/assets/images/group43.svg
    - packages/testing/assets/images/path2248.svg
    - packages/testing/assets/images/path2249.svg
    - packages/testing/assets/images/group44.svg
    - packages/testing/assets/images/path2283.svg
    - packages/testing/assets/images/path2284.svg
    - packages/testing/assets/images/path2285.svg
    - packages/testing/assets/images/group45.svg
    - packages/testing/assets/images/path2289.svg
    - packages/testing/assets/images/path2290.svg
    - packages/testing/assets/images/path2291.svg
    - packages/testing/assets/images/group46.svg
    - packages/testing/assets/images/group47.svg
    - packages/testing/assets/images/group48.svg
    - packages/testing/assets/images/path2332.svg
    - packages/testing/assets/images/path2333.svg
    - packages/testing/assets/images/group49.svg
    - packages/testing/assets/images/image.png
    - packages/testing/assets/images/whatsappimage20210313at22pm1.png
    - packages/testing/assets/images/dribbble.svg
    - packages/testing/assets/images/icomoonfreebehance2.svg
    - packages/testing/assets/images/bg.svg
    - packages/testing/assets/images/image5.png
    - packages/testing/assets/images/image6.png
    - packages/testing/assets/images/image4.png
    - packages/testing/assets/images/ellipse97.png
    - packages/testing/assets/images/shadow.png
    - packages/testing/assets/images/main.png
    - packages/testing/assets/images/iphonexmockuplabel.png
    - packages/testing/assets/images/line1.svg
    - packages/testing/assets/images/antdesignheartfilled.svg
